name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: go mod tidy && git diff --exit-code go.mod go.sum
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '1.20' ]
    name: Go ${{ matrix.version }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}
      - uses: actions/checkout@v3
      - run: go vet ./...
      - run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v --procs=N --compilers=N --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --coverprofile=cover.profile --race --trace --json-report=report.json --timeout=TIMEOUT --poll-progress-after=Xs --poll-progress-interval=Ys

# run: go run ./ginkgo -r -randomize-all -randomize-suites -race -trace -procs=2 -poll-progress-after=10s -poll-progress-interval=10sour project.